"""
predict.py

Predict whether a URL is phishing or legitimate
using the trained Random Forest model.

INPUT:
    A URL provided by the user.

MODEL:
    models/phishing_model.pkl

FEATURES:
    22 features generated by feature_extractor.py

LABEL:
    0 = Phishing
    1 = Legitimate


PIPELINE:

    New URL
       |
       v
    feature_extractor.py
       |
       v
    22 Features
       |
       v
    phishing_model.pkl
       |
       v
    Prediction
       |
       +----> Phishing
       |
       +----> Legitimate
"""


import os
import pickle

import pandas as pd

from feature_extractor import (
    extract_features,
    ALL_FEATURES
)


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MODEL_FILE = os.path.join(
    PROJECT_ROOT,
    "models",
    "phishing_model.pkl"
)


# ============================================================
# LOAD TRAINED MODEL
# ============================================================

def load_model():
    """
    Load the trained Random Forest model.

    Returns
    -------
    model
        Trained Random Forest classifier.
    """

    print("\n" + "=" * 70)
    print("LOADING PHISHING DETECTION MODEL")
    print("=" * 70)

    if not os.path.exists(
        MODEL_FILE
    ):

        raise FileNotFoundError(
            f"\nTrained model not found:\n"
            f"{MODEL_FILE}\n\n"
            f"Run train_model.py first."
        )

    try:

        with open(
            MODEL_FILE,
            "rb"
        ) as file:

            model = pickle.load(
                file
            )

    except Exception as error:

        raise RuntimeError(
            f"Unable to load model: {error}"
        )

    # --------------------------------------------------------
    # Verify model capabilities
    # --------------------------------------------------------

    if not hasattr(
        model,
        "predict"
    ):

        raise ValueError(
            "Loaded object does not support prediction."
        )

    if not hasattr(
        model,
        "predict_proba"
    ):

        raise ValueError(
            "Loaded model does not support probability prediction."
        )

    print(
        "✓ Model loaded successfully."
    )

    return model


# ============================================================
# VALIDATE URL
# ============================================================

def validate_url(url):
    """
    Basic validation of user-provided URL.
    """

    if url is None:

        return False

    url = str(
        url
    ).strip()

    if not url:

        return False

    return True


# ============================================================
# EXTRACT FEATURES
# ============================================================

def extract_url_features(url):
    """
    Extract the same 22 features used during training.

    Returns
    -------
    pandas.DataFrame
        One-row DataFrame with the exact feature order.
    """

    print("\n" + "=" * 70)
    print("EXTRACTING 22 FEATURES")
    print("=" * 70)

    try:

        features = extract_features(
            url
        )

    except Exception as error:

        raise RuntimeError(
            f"Feature extraction failed: {error}"
        )

    # --------------------------------------------------------
    # Verify exact feature set
    # --------------------------------------------------------

    if set(features.keys()) != set(
        ALL_FEATURES
    ):

        missing = (
            set(ALL_FEATURES)
            - set(features.keys())
        )

        extra = (
            set(features.keys())
            - set(ALL_FEATURES)
        )

        raise ValueError(
            f"\nFeature mismatch.\n"
            f"Missing: {missing}\n"
            f"Extra: {extra}"
        )

    # --------------------------------------------------------
    # Create DataFrame in EXACT training order
    # --------------------------------------------------------

    feature_vector = [
        features[name]
        for name in ALL_FEATURES
    ]

    X = pd.DataFrame(
        [
            feature_vector
        ],
        columns=ALL_FEATURES
    )

    # --------------------------------------------------------
    # Convert all values to numeric
    # --------------------------------------------------------

    for feature in ALL_FEATURES:

        X[feature] = pd.to_numeric(
            X[feature],
            errors="coerce"
        )

    # --------------------------------------------------------
    # Validate values
    # --------------------------------------------------------

    if X.isna().any().any():

        invalid_features = (
            X.columns[
                X.isna().any()
            ].tolist()
        )

        raise ValueError(
            "Invalid feature values found in: "
            + ", ".join(
                invalid_features
            )
        )

    print(
        "✓ 22 features extracted."
    )

    return X, features


# ============================================================
# DISPLAY FEATURES
# ============================================================

def display_features(features):
    """
    Display all 22 extracted features.
    """

    print("\n" + "-" * 70)
    print("EXTRACTED FEATURES")
    print("-" * 70)

    for number, feature in enumerate(
        ALL_FEATURES,
        start=1
    ):

        print(
            f"{number:02d}. "
            f"{feature:<28}: "
            f"{features[feature]}"
        )


# ============================================================
# PREDICT URL
# ============================================================

def predict_url(
    model,
    X
):
    """
    Predict URL class and probability.

    Returns
    -------
    prediction : int
        0 = Phishing
        1 = Legitimate

    phishing_probability : float

    legitimate_probability : float
    """

    print("\n" + "=" * 70)
    print("RUNNING PHISHING DETECTION")
    print("=" * 70)

    # --------------------------------------------------------
    # Class prediction
    # --------------------------------------------------------

    prediction = int(
        model.predict(
            X
        )[0]
    )

    # --------------------------------------------------------
    # Probability prediction
    # --------------------------------------------------------

    probabilities = (
        model.predict_proba(
            X
        )[0]
    )

    # --------------------------------------------------------
    # Find probability corresponding to each class.
    #
    # Do NOT assume probability index 0/1 without checking
    # model.classes_.
    # --------------------------------------------------------

    class_probabilities = dict(
        zip(
            model.classes_,
            probabilities
        )
    )

    phishing_probability = (
        float(
            class_probabilities.get(
                0,
                0
            )
        )
        * 100
    )

    legitimate_probability = (
        float(
            class_probabilities.get(
                1,
                0
            )
        )
        * 100
    )

    return (
        prediction,
        phishing_probability,
        legitimate_probability
    )


# ============================================================
# DISPLAY RESULT
# ============================================================

def display_result(
    url,
    prediction,
    phishing_probability,
    legitimate_probability
):
    """
    Display the final phishing detection result.
    """

    print("\n")
    print("=" * 70)
    print("PHISHING DETECTION RESULT")
    print("=" * 70)

    print(
        f"\nURL:"
    )

    print(
        url
    )

    print(
        "\nPrediction:"
    )

    if prediction == 0:

        print(
            "\n⚠️  PHISHING URL"
        )

        print(
            "The model classified this URL "
            "as potentially malicious/phishing."
        )

    elif prediction == 1:

        print(
            "\n✅ LEGITIMATE URL"
        )

        print(
            "The model classified this URL "
            "as likely legitimate."
        )

    else:

        print(
            "\nUNKNOWN CLASS"
        )

    print(
        "\nModel confidence:"
    )

    print(
        f"Phishing probability   : "
        f"{phishing_probability:.2f}%"
    )

    print(
        f"Legitimate probability : "
        f"{legitimate_probability:.2f}%"
    )

    print(
        "\n" + "=" * 70
    )

    # --------------------------------------------------------
    # Security recommendation
    # --------------------------------------------------------

    if prediction == 0:

        print(
            "RECOMMENDATION:"
        )

        print(
            "Do not enter passwords, OTPs, "
            "banking information, or other "
            "sensitive information on this website."
        )

    else:

        print(
            "RECOMMENDATION:"
        )

        print(
            "The URL appears legitimate according "
            "to the trained model. Still verify "
            "the website before entering sensitive data."
        )

    print(
        "=" * 70
    )


# ============================================================
# PREDICT FUNCTION
# ============================================================

def predict(
    url,
    model=None
):
    """
    Complete prediction function.

    This function can later be imported by:
        app.py
        Flask
        Streamlit
        FastAPI
        GUI applications

    Parameters
    ----------
    url : str
        URL to analyze.

    model : optional
        Already-loaded model.

    Returns
    -------
    dict
        Prediction result.
    """

    # --------------------------------------------------------
    # Validate URL
    # --------------------------------------------------------

    if not validate_url(
        url
    ):

        raise ValueError(
            "Please provide a valid URL."
        )

    url = str(
        url
    ).strip()

    # --------------------------------------------------------
    # Load model if necessary
    # --------------------------------------------------------

    if model is None:

        model = load_model()

    # --------------------------------------------------------
    # Extract features
    # --------------------------------------------------------

    X, features = extract_url_features(
        url
    )

    # --------------------------------------------------------
    # Predict
    # --------------------------------------------------------

    (
        prediction,
        phishing_probability,
        legitimate_probability
    ) = predict_url(
        model,
        X
    )

    # --------------------------------------------------------
    # Create result
    # --------------------------------------------------------

    result = {

        "url": url,

        "prediction": prediction,

        "label": (
            "Phishing"
            if prediction == 0
            else "Legitimate"
        ),

        "phishing_probability":
            phishing_probability,

        "legitimate_probability":
            legitimate_probability,

        "features":
            features
    }

    return result


# ============================================================
# INTERACTIVE MODE
# ============================================================

def interactive_mode():
    """
    Run the detector interactively from the terminal.
    """

    print("\n")
    print("=" * 70)
    print("AI PHISHING DETECTION SYSTEM")
    print("=" * 70)

    print(
        "\nEnter a URL to analyze."
    )

    print(
        "Type 'exit' to close the program."
    )

    # --------------------------------------------------------
    # Load model once
    # --------------------------------------------------------

    model = load_model()

    # --------------------------------------------------------
    # Continuous prediction loop
    # --------------------------------------------------------

    while True:

        print(
            "\n" + "-" * 70
        )

        url = input(
            "Enter URL: "
        ).strip()

        # ----------------------------------------------------
        # Exit
        # ----------------------------------------------------

        if url.lower() in {
            "exit",
            "quit",
            "q"
        }:

            print(
                "\nExiting AI Phishing Detection System."
            )

            break

        # ----------------------------------------------------
        # Validate
        # ----------------------------------------------------

        if not validate_url(
            url
        ):

            print(
                "\n❌ Please enter a URL."
            )

            continue

        try:

            # ================================================
            # Extract features
            # ================================================

            X, features = (
                extract_url_features(
                    url
                )
            )

            # ================================================
            # Display features
            # ================================================

            display_features(
                features
            )

            # ================================================
            # Predict
            # ================================================

            (
                prediction,
                phishing_probability,
                legitimate_probability
            ) = predict_url(
                model,
                X
            )

            # ================================================
            # Display result
            # ================================================

            display_result(
                url,
                prediction,
                phishing_probability,
                legitimate_probability
            )

        except Exception as error:

            print(
                "\n❌ ERROR:"
            )

            print(
                error
            )


# ============================================================
# TEST SINGLE URL
# ============================================================

def test_single_url():
    """
    Test the detector with a predefined URL.

    This is useful for checking that the complete
    prediction pipeline works.
    """

    test_url = (
        "https://www.google.com"
    )

    print(
        f"\nTesting URL:"
    )

    print(
        test_url
    )

    model = load_model()

    X, features = (
        extract_url_features(
            test_url
        )
    )

    display_features(
        features
    )

    (
        prediction,
        phishing_probability,
        legitimate_probability
    ) = predict_url(
        model,
        X
    )

    display_result(
        test_url,
        prediction,
        phishing_probability,
        legitimate_probability
    )


# ============================================================
# MAIN
# ============================================================

def main():

    interactive_mode()


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()
